require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/limits", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Limit. As you add validations to Limit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Limit.create! valid_attributes
      get limits_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      limit = Limit.create! valid_attributes
      get limit_url(limit)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_limit_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      limit = Limit.create! valid_attributes
      get edit_limit_url(limit)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Limit" do
        expect {
          post limits_url, params: { limit: valid_attributes }
        }.to change(Limit, :count).by(1)
      end

      it "redirects to the created limit" do
        post limits_url, params: { limit: valid_attributes }
        expect(response).to redirect_to(limit_url(Limit.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Limit" do
        expect {
          post limits_url, params: { limit: invalid_attributes }
        }.to change(Limit, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post limits_url, params: { limit: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested limit" do
        limit = Limit.create! valid_attributes
        patch limit_url(limit), params: { limit: new_attributes }
        limit.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the limit" do
        limit = Limit.create! valid_attributes
        patch limit_url(limit), params: { limit: new_attributes }
        limit.reload
        expect(response).to redirect_to(limit_url(limit))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        limit = Limit.create! valid_attributes
        patch limit_url(limit), params: { limit: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested limit" do
      limit = Limit.create! valid_attributes
      expect {
        delete limit_url(limit)
      }.to change(Limit, :count).by(-1)
    end

    it "redirects to the limits list" do
      limit = Limit.create! valid_attributes
      delete limit_url(limit)
      expect(response).to redirect_to(limits_url)
    end
  end
end
